### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by gugakatsi** [Taishi-Y/FlipProgressDialog#1]
Error:(57, 13) Failed to resolve: com.taishi-y:flipprogressdialog:0.1.0
<somedir/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Taishi-Y** [comment]
Thanks man! I'm going to add this lib to jcenter. It will takes 2 hours or so!

**Comment by gugakatsi** [comment]
thank you , btw it's best loading lib i've ever seen. keep it up.

**Comment by Taishi-Y** [comment]
Aww Thank you! XD

**Comment by gugakatsi** [comment]
@Taishi-Y I just go that i can't show the dialog without fragment manager , can you explain why or if i can escape it somehow :laughing:

**Comment by Taishi-Y** [comment]
@gugakatsi Thank you for asking! Because FlipProgressDialog class extends DialogFragment and using show function.😅
Do you know any better way?

**Comment by gugakatsi** [comment]
nah :smile:  thanks  
:D
